export const stockIndicesData = [
  {
    title: "NIFTY 50",
    symbol: "NSE: NIFTY",
    desc: "Tracks the top 50 large-cap companies listed on NSE India.",
    currentValue: 22543.65,
    change: -112.40,
    percentChange: -0.50,
    status: "loss",
  },
  {
    title: "SENSEX",
    symbol: "BSE: SENSEX",
    desc: "Represents 30 major companies listed on the Bombay Stock Exchange.",
    currentValue: 74321.82,
    change: -275.36,
    percentChange: -0.37,
    status: "loss",
  },
  {
    title: "NASDAQ 100",
    symbol: "NASDAQ: NDX",
    desc: "Includes the largest non-financial companies listed on NASDAQ.",
    currentValue: 18625.14,
    change: 102.57,
    percentChange: 0.55,
    status: "gain",
  },
  {
    title: "S&P 500",
    symbol: "SPX",
    desc: "Tracks performance of 500 large U.S. companies across sectors.",
    currentValue: 5523.74,
    change: 18.63,
    percentChange: 0.34,
    status: "gain",
  },
  {
    title: "DOW JONES",
    symbol: "DJI",
    desc: "Comprises 30 prominent companies from various U.S. industries.",
    currentValue: 39245.62,
    change: -76.81,
    percentChange: -0.20,
    status: "loss",
  },
  {
    title: "FTSE 100",
    symbol: "FTSE",
    desc: "Represents the 100 largest companies listed on the London Stock Exchange.",
    currentValue: 8290.42,
    change: 24.67,
    percentChange: 0.30,
    status: "gain",
  },
  {
    title: "NIKKEI 225",
    symbol: "NIKKEI",
    desc: "Japan’s premier stock index tracking top 225 Tokyo-listed companies.",
    currentValue: 38754.61,
    change: -145.93,
    percentChange: -0.38,
    status: "loss",
  },
  {
    title: "HANG SENG",
    symbol: "HSI",
    desc: "Hong Kong’s benchmark index reflecting major local companies.",
    currentValue: 17985.25,
    change: 120.44,
    percentChange: 0.67,
    status: "gain",
  },
  {
    title: "DAX",
    symbol: "DAX",
    desc: "Tracks 40 major blue-chip companies listed on the Frankfurt Exchange.",
    currentValue: 18072.53,
    change: 54.12,
    percentChange: 0.30,
    status: "gain",
  },
  {
    title: "CAC 40",
    symbol: "CAC",
    desc: "Represents 40 largest companies listed on the Paris Stock Exchange.",
    currentValue: 7809.44,
    change: -42.18,
    percentChange: -0.54,
    status: "loss",
  },
];
