export const stockIndicesData = [
  {
    title: "NIFTY 50",
    symbol: "NSE: NIFTY",
    desc: "Tracks the top 50 large-cap companies listed on NSE India.",
    currentValue: 22543.65,
    change: -112.40,
    percentChange: -0.50,
    status: "loss",
  },
  {
    title: "SENSEX",
    symbol: "BSE: SENSEX",
    desc: "Represents 30 major companies listed on the Bombay Stock Exchange.",
    currentValue: 74520.12,
    change: 268.90,
    percentChange: 0.36,
    status: "gain",
  },
  {
    title: "NIFTY BANK",
    symbol: "NSE: BANKNIFTY",
    desc: "Tracks the performance of the banking sector, including major banks.",
    currentValue: 47680.25,
    change: -180.75,
    percentChange: -0.38,
    status: "loss",
  },
  {
    title: "NIFTY IT",
    symbol: "NSE: NIFTYIT",
    desc: "Represents major IT and software companies in India.",
    currentValue: 36542.90,
    change: 420.80,
    percentChange: 1.17,
    status: "gain",
  },
  {
    title: "NIFTY AUTO",
    symbol: "NSE: NIFTYAUTO",
    desc: "Captures performance of automobile sector companies.",
    currentValue: 19210.45,
    change: -95.35,
    percentChange: -0.49,
    status: "loss",
  },
  {
    title: "NIFTY FMCG",
    symbol: "NSE: NIFTYFMCG",
    desc: "Includes top companies in the fast-moving consumer goods sector.",
    currentValue: 5450.35,
    change: 22.10,
    percentChange: 0.41,
    status: "gain",
  },
  {
    title: "NIFTY PHARMA",
    symbol: "NSE: NIFTYPHARMA",
    desc: "Represents top pharmaceutical and healthcare companies in India.",
    currentValue: 18345.20,
    change: 65.90,
    percentChange: 0.36,
    status: "gain",
  },
  {
    title: "NIFTY METAL",
    symbol: "NSE: NIFTYMETAL",
    desc: "Tracks performance of metal and mining sector companies.",
    currentValue: 8250.15,
    change: -45.10,
    percentChange: -0.54,
    status: "loss",
  },
  {
    title: "NIFTY ENERGY",
    symbol: "NSE: NIFTYENERGY",
    desc: "Represents top energy sector companies including oil, gas, and power.",
    currentValue: 32040.65,
    change: 175.80,
    percentChange: 0.55,
    status: "gain",
  },
  {
    title: "NIFTY REALTY",
    symbol: "NSE: NIFTYREALTY",
    desc: "Captures performance of real estate sector companies.",
    currentValue: 870.30,
    change: -6.25,
    percentChange: -0.71,
    status: "loss",
  },
  {
    title: "NIFTY PSU BANK",
    symbol: "NSE: NIFTYPSUBANK",
    desc: "Tracks performance of public sector banks in India.",
    currentValue: 6250.70,
    change: 58.40,
    percentChange: 0.94,
    status: "gain",
  },
  {
    title: "NIFTY PRIVATE BANK",
    symbol: "NSE: NIFTYPVTBANK",
    desc: "Includes leading private sector banks in India.",
    currentValue: 24790.25,
    change: -120.55,
    percentChange: -0.48,
    status: "loss",
  },
  {
    title: "NIFTY HEALTHCARE INDEX",
    symbol: "NSE: NIFTYHEALTHCARE",
    desc: "Captures companies from pharmaceuticals, hospitals, and healthcare.",
    currentValue: 11650.90,
    change: 110.75,
    percentChange: 0.96,
    status: "gain",
  },
  {
    title: "NIFTY MIDCAP 100",
    symbol: "NSE: NIFTYMIDCAP100",
    desc: "Tracks performance of 100 mid-sized companies listed on NSE.",
    currentValue: 51325.65,
    change: -320.40,
    percentChange: -0.62,
    status: "loss",
  },
  {
    title: "NIFTY SMALLCAP 100",
    symbol: "NSE: NIFTYSMALLCAP100",
    desc: "Represents the 100 small-cap companies traded on the NSE.",
    currentValue: 16785.45,
    change: 185.30,
    percentChange: 1.12,
    status: "gain",
  }
];
